### ISSUE TITLE
Would love to see a function to acces the route url by as parameter in route file

### ISSUE THREAD

**Issue by martijnderidder** [mace015/MaceVC#2]
When i am programming in a view, i want to acces the routes file by the 'as' attribute.
So for an example:

`$router->get('/users', array('middleware' => '\Middleware\ClosedMiddleware', 'as' => 'users.index', 'uses' => 'UsersController@index'));`

I would love to see in a option so i can acces it like we do already with asset().
So it would be something linke:

`<a href="{{ route('users.index') }}">Users</a>`

**Comment by mace015** [comment]
This has been added in 0.8 which will be released later today, see the change log for more information.
