### ISSUE TITLE
When a directory already existst in the public directory the site redirects to base url.

### ISSUE THREAD

**Issue by martijnderidder** [mace015/MaceVC#5]
I have a program on my url: http://new.app:8000

When i have a directory called: /public/users for example, i cant use '/users' anymore in my routes. That seems fine, but when i go the url, the system dont show an error and redirects me to http://new.app, without the port. I expected some kind of error?

Good, when i rename the directory to: /usersDesign, i still cant use the '/users' route.

**Comment by mace015** [comment]
This is a bug with Homestead/Browsers!
