### ISSUE TITLE
It would be nice to have a form value function

### ISSUE THREAD

**Issue by martijnderidder** [mace015/MaceVC#8]
When you submit a form, you don't want that your user have to fill in all information again. So maybe it is a good idea to include a form value function. It will come with 2 options. The new and the old value.
The new value will be the value from the input, the old value will be empty or comes from a database.

So you get something like this:
`<input type="text" name="username" value="{{ formValue($_POST['username'], $user->username) }}">`

Maybe this include a Input class? For handeling input from a form.

**Comment by mace015** [comment]
A helper function, newOld() has been added in 0.8, see the change log for more information.
